type route = { name : string; wire : Provider.api; endpoint : string }

type descriptor = {
  id : string;
  display_name : string;
  routes : route list;
  default_route : string;
  api_key_env : string option;
  oauth : string option;
}

(* Adding a compatible provider changes only this list. New wire protocols get
   their own adapter in Provider; an absent route must never be guessed. *)
let builtins = [
  { id = "openai"; display_name = "OpenAI";
    routes = [
      { name = "chat"; wire = Provider.Openai_completions;
        endpoint = "https://api.openai.com/v1/chat/completions" };
      { name = "responses"; wire = Provider.Openai_responses;
        endpoint = "https://api.openai.com/v1/responses" } ];
    default_route = "responses";
    api_key_env = Some "OPENAI_API_KEY";
    oauth = None };
  { id = "openai-codex"; display_name = "OpenAI Codex subscription";
    routes = [ { name = "responses"; wire = Provider.Codex_responses;
      endpoint = "https://chatgpt.com/backend-api/codex/responses" } ];
    default_route = "responses";
    api_key_env = None; oauth = Some "openai-codex" };
  { id = "anthropic"; display_name = "Anthropic";
    routes = [ { name = "messages"; wire = Provider.Anthropic_messages;
      endpoint = "https://api.anthropic.com/v1/messages" } ];
    default_route = "messages";
    api_key_env = Some "ANTHROPIC_API_KEY";
    oauth = Some "anthropic" };
  { id = "ollama"; display_name = "Ollama (local)";
    routes = [ { name = "chat"; wire = Provider.Ollama_chat;
      endpoint = "http://127.0.0.1:11434/api/chat" } ];
    default_route = "chat";
    api_key_env = None; oauth = None };
  { id = "ollama-cloud"; display_name = "Ollama Cloud";
    routes = [ { name = "chat"; wire = Provider.Ollama_chat;
      endpoint = Ollama_cloud.chat_url } ];
    default_route = "chat";
    api_key_env = Some "OLLAMA_CLOUD_API_KEY"; oauth = None };
  { id = "google"; display_name = "Google Gemini API";
    routes = [ { name = "generate"; wire = Provider.Gemini_direct;
      endpoint = "https://generativelanguage.googleapis.com/v1beta/models" } ];
    default_route = "generate";
    api_key_env = Some "GEMINI_API_KEY"; oauth = None };
  { id = "google-vertex"; display_name = "Google Vertex AI (configured project)";
    routes = [ { name = "generate"; wire = Provider.Vertex_generate;
      endpoint = "" } ];
    default_route = "generate";
    api_key_env = None; oauth = None };
  { id = "amazon-bedrock"; display_name = "Amazon Bedrock Converse (configured region)";
    routes = [ { name = "converse"; wire = Provider.Bedrock_converse;
      endpoint = "" } ];
    default_route = "converse";
    api_key_env = None; oauth = None };
  { id = "bedrock-mantle"; display_name = "AWS Bedrock Mantle (configured region)";
    routes = [ { name = "responses"; wire = Provider.Bedrock_mantle_responses;
      endpoint = "" } ];
    default_route = "responses";
    api_key_env = Some "AWS_BEARER_TOKEN_BEDROCK"; oauth = None };
  { id = "xai"; display_name = "xAI";
    routes = [ { name = "chat"; wire = Provider.Xai_chat;
      endpoint = Xai_api.chat_url } ];
    default_route = "chat";
    api_key_env = Some "XAI_API_KEY"; oauth = None };
  { id = "nvidia"; display_name = "NVIDIA hosted NIM";
    routes = [ { name = "chat"; wire = Provider.Nvidia_chat;
      endpoint = Nvidia_api.chat_url } ];
    default_route = "chat";
    api_key_env = Some "NVIDIA_API_KEY"; oauth = None };
  { id = "novita"; display_name = "Novita AI";
    routes = [ { name = "chat"; wire = Provider.Novita_chat;
      endpoint = Novita_api.chat_url } ];
    default_route = "chat";
    api_key_env = Some "NOVITA_API_KEY"; oauth = None };
  { id = "siliconflow"; display_name = "SiliconFlow (global)";
    routes = [ { name = "chat"; wire = Provider.Siliconflow_chat;
      endpoint = Siliconflow_api.chat_url } ];
    default_route = "chat";
    api_key_env = Some "SILICONFLOW_API_KEY"; oauth = None };
  { id = "siliconflow-cn"; display_name = "SiliconFlow (China)";
    routes = [ { name = "chat"; wire = Provider.Siliconflow_cn_chat;
      endpoint = Siliconflow_api.cn_chat_url } ];
    default_route = "chat";
    api_key_env = Some "SILICONFLOW_CN_API_KEY"; oauth = None };
  { id = "stepfun"; display_name = "StepFun (international, unclassified model IDs)";
    routes = [ { name = "chat"; wire = Provider.Stepfun_chat;
      endpoint = Stepfun_api.chat_url } ];
    default_route = "chat";
    api_key_env = Some "STEPFUN_API_KEY"; oauth = None };
  { id = "coreweave"; display_name = "CoreWeave Serverless (W&B Inference)";
    routes = [ { name = "chat"; wire = Provider.Coreweave_chat;
      endpoint = Coreweave_api.chat_url } ];
    default_route = "chat";
    api_key_env = Some "COREWEAVE_API_KEY"; oauth = None };
  { id = "synthetic"; display_name = "Synthetic (unclassified model IDs)";
    routes = [ { name = "chat"; wire = Provider.Synthetic_chat;
      endpoint = Synthetic_api.chat_url } ];
    default_route = "chat";
    api_key_env = Some "SYNTHETIC_API_KEY"; oauth = None };
  { id = "zai"; display_name = "Z.AI (standard Chat)";
    routes = [ { name = "chat"; wire = Provider.Zai_chat;
      endpoint = Zai_api.chat_url } ];
    default_route = "chat";
    api_key_env = Some "ZAI_API_KEY"; oauth = None };
  { id = "zenmux"; display_name = "ZenMux (unclassified model IDs)";
    routes = [ { name = "chat"; wire = Provider.Zenmux_chat;
      endpoint = Zenmux_api.chat_url } ];
    default_route = "chat";
    api_key_env = Some "ZENMUX_API_KEY"; oauth = None };
  { id = "wafer-serverless"; display_name = "Wafer Serverless (unclassified model IDs)";
    routes = [ { name = "chat"; wire = Provider.Wafer_chat;
      endpoint = Wafer_api.chat_url } ];
    default_route = "chat";
    api_key_env = Some "WAFER_SERVERLESS_API_KEY"; oauth = None };
  { id = "qianfan"; display_name = "Baidu Qianfan V2";
    routes = [ { name = "chat"; wire = Provider.Qianfan_chat;
      endpoint = Qianfan_api.chat_url } ];
    default_route = "chat";
    api_key_env = Some "QIANFAN_API_KEY"; oauth = None };
  { id = "xiaomi"; display_name = "Xiaomi MiMo pay-as-you-go (unclassified IDs)";
    routes = [ { name = "chat"; wire = Provider.Xiaomi_chat;
      endpoint = Xiaomi_api.chat_url } ];
    default_route = "chat";
    api_key_env = Some "XIAOMI_API_KEY"; oauth = None };
  { id = "kilo"; display_name = "Kilo Gateway (public unclassified IDs)";
    routes = [ { name = "chat"; wire = Provider.Kilo_chat;
      endpoint = Kilo_api.chat_url } ];
    default_route = "chat";
    api_key_env = Some "KILO_API_KEY"; oauth = Some "kilo" };
  { id = "alibaba-coding-plan"; display_name = "Alibaba Coding Plan (select region)";
    routes = [
      { name = "china"; wire = Provider.Alibaba_coding_chat;
        endpoint = Alibaba_coding_api.china_chat_url };
      { name = "intl"; wire = Provider.Alibaba_coding_chat;
        endpoint = Alibaba_coding_api.intl_chat_url } ];
    default_route = "select-region";
    api_key_env = Some "ALIBABA_CODING_PLAN_API_KEY"; oauth = None };
  { id = "singularityapi-dev"; display_name = "SingularityAPI universal";
    routes = [ { name = "chat"; wire = Provider.Singularity_dev_chat;
      endpoint = Singularity_dev_api.chat_url } ];
    default_route = "chat";
    api_key_env = Some "SINGULARITYAPI_DEV_API_KEY"; oauth = None };
  { id = "opencode-zen"; display_name = "OpenCode Zen (explicit Responses, public unclassified IDs)";
    routes = [ { name = "responses"; wire = Provider.Opencode_zen_responses;
      endpoint = Opencode_zen_api.responses_url } ];
    default_route = "responses";
    api_key_env = Some "OPENCODE_API_KEY"; oauth = None };
  { id = "opencode-go"; display_name = "OpenCode Go (explicit Chat, public unclassified IDs)";
    routes = [ { name = "chat"; wire = Provider.Opencode_go_chat;
      endpoint = Opencode_go_api.chat_url } ];
    default_route = "chat";
    api_key_env = Some "OPENCODE_API_KEY"; oauth = None };
  { id = "charm-hyper"; display_name = "Charm Hyper (public unclassified IDs)";
    routes = [ { name = "chat"; wire = Provider.Charm_hyper_chat;
      endpoint = Charm_hyper_api.chat_url } ];
    default_route = "chat";
    api_key_env = Some "CHARM_HYPER_API_KEY"; oauth = None };
  { id = "singularityapi-tech"; display_name = "SingularityAPI reserved lane (unverified entitlement)";
    routes = [ { name = "chat"; wire = Provider.Singularity_tech_chat;
      endpoint = Singularity_tech_api.chat_url } ];
    default_route = "chat";
    api_key_env = Some "SINGULARITYAPI_TECH_API_KEY"; oauth = None };
  { id = "firepass"; display_name = "Fire Pass (manual full router ID)";
    routes = [ { name = "chat"; wire = Provider.Firepass_chat;
      endpoint = Firepass_api.chat_url } ];
    default_route = "chat";
    api_key_env = Some "FIREPASS_API_KEY"; oauth = None };
  { id = "yolo-auto"; display_name = "Yolo Auto (unclassified model IDs)";
    routes = [ { name = "chat"; wire = Provider.Yolo_auto_chat;
      endpoint = Yolo_auto_api.chat_url } ];
    default_route = "chat";
    api_key_env = Some "YOLO_AUTO_API_KEY"; oauth = None };
  { id = "xiaomi-token-plan-ams"; display_name = "Xiaomi MiMo Token Plan (Americas)";
    routes = [ { name = "chat"; wire = Provider.Xiaomi_token_ams_chat;
      endpoint = Xiaomi_token_api.chat_url Xiaomi_token_api.Ams } ];
    default_route = "chat";
    api_key_env = Some "XIAOMI_TOKEN_PLAN_AMS_API_KEY"; oauth = None };
  { id = "xiaomi-token-plan-cn"; display_name = "Xiaomi MiMo Token Plan (China)";
    routes = [ { name = "chat"; wire = Provider.Xiaomi_token_cn_chat;
      endpoint = Xiaomi_token_api.chat_url Xiaomi_token_api.Cn } ];
    default_route = "chat";
    api_key_env = Some "XIAOMI_TOKEN_PLAN_CN_API_KEY"; oauth = None };
  { id = "xiaomi-token-plan-sgp"; display_name = "Xiaomi MiMo Token Plan (Singapore)";
    routes = [ { name = "chat"; wire = Provider.Xiaomi_token_sgp_chat;
      endpoint = Xiaomi_token_api.chat_url Xiaomi_token_api.Sgp } ];
    default_route = "chat";
    api_key_env = Some "XIAOMI_TOKEN_PLAN_SGP_API_KEY"; oauth = None };
  { id = "minimax-code"; display_name = "MiniMax Token Plan (international)";
    routes = [ { name = "chat"; wire = Provider.Minimax_code_chat;
      endpoint = Minimax_code_api.intl_chat_url } ];
    default_route = "chat";
    api_key_env = Some "MINIMAX_CODE_API_KEY"; oauth = None };
  { id = "minimax-code-cn"; display_name = "MiniMax Token Plan (China)";
    routes = [ { name = "chat"; wire = Provider.Minimax_code_cn_chat;
      endpoint = Minimax_code_api.china_chat_url } ];
    default_route = "chat";
    api_key_env = Some "MINIMAX_CODE_CN_API_KEY"; oauth = None };
  { id = "meta"; display_name = "Meta Model API (explicit Responses)";
    routes = [ { name = "responses"; wire = Provider.Meta_responses;
      endpoint = Meta_api.responses_url } ];
    default_route = "responses";
    api_key_env = Some "MODEL_API_KEY"; oauth = None };
  { id = "vercel-ai-gateway"; display_name = "Vercel AI Gateway (unclassified model IDs)";
    routes = [ { name = "chat"; wire = Provider.Vercel_ai_gateway_chat;
      endpoint = Vercel_ai_gateway_api.chat_url } ];
    default_route = "chat";
    api_key_env = Some "AI_GATEWAY_API_KEY"; oauth = None };
  { id = "cloudflare-ai-gateway"; display_name = "Cloudflare AI Gateway (configured account/gateway)";
    routes = [ { name = "chat"; wire = Provider.Cloudflare_ai_gateway_chat;
      endpoint = "" } ];
    default_route = "chat";
    api_key_env = Some "CLOUDFLARE_AI_GATEWAY_API_KEY"; oauth = None };
  { id = "commandcode"; display_name = "Command Code Studio Provider API (choose route)";
    routes = [
      { name = "chat"; wire = Provider.Commandcode_chat;
        endpoint = Commandcode_api.chat_url };
      { name = "messages"; wire = Provider.Commandcode_messages;
        endpoint = Commandcode_api.messages_url };
      { name = "responses"; wire = Provider.Commandcode_responses;
        endpoint = Commandcode_api.responses_url } ];
    default_route = "select-route";
    api_key_env = Some "COMMAND_CODE_API_KEY"; oauth = None };
  { id = "devin"; display_name = "Devin CLI (account-scoped Connect)";
    routes = [ { name = "connect"; wire = Provider.Devin_connect;
      endpoint = Devin_api.chat_url } ];
    default_route = "connect";
    api_key_env = Some "DEVIN_API_KEY"; oauth = Some "devin" };
  { id = "gitlab-duo"; display_name = "GitLab Duo Direct Access (manual upstream model/route)";
    routes = [
      { name = "messages"; wire = Provider.Gitlab_duo_messages;
        endpoint = Gitlab_duo_api.anthropic_url };
      { name = "responses"; wire = Provider.Gitlab_duo_responses;
        endpoint = Gitlab_duo_api.responses_url };
      { name = "chat"; wire = Provider.Gitlab_duo_chat;
        endpoint = Gitlab_duo_api.completions_url } ];
    default_route = "select-route";
    api_key_env = Some "GITLAB_TOKEN"; oauth = Some "gitlab-duo" };
  { id = "moonshot"; display_name = "Moonshot AI (global)";
    routes = [ { name = "chat"; wire = Provider.Openai_completions;
      endpoint = "https://api.moonshot.ai/v1/chat/completions" } ];
    default_route = "chat";
    api_key_env = Some "MOONSHOT_API_KEY"; oauth = None };
  { id = "deepseek"; display_name = "DeepSeek";
    routes = [ { name = "chat"; wire = Provider.Openai_completions;
      endpoint = "https://api.deepseek.com/chat/completions" } ];
    default_route = "chat";
    api_key_env = Some "DEEPSEEK_API_KEY"; oauth = None };
  { id = "groq"; display_name = "Groq";
    routes = [ { name = "chat"; wire = Provider.Openai_completions;
      endpoint = "https://api.groq.com/openai/v1/chat/completions" } ];
    default_route = "chat";
    api_key_env = Some "GROQ_API_KEY"; oauth = None };
  { id = "mistral"; display_name = "Mistral";
    routes = [ { name = "chat"; wire = Provider.Openai_completions;
      endpoint = "https://api.mistral.ai/v1/chat/completions" } ];
    default_route = "chat";
    api_key_env = Some "MISTRAL_API_KEY"; oauth = None };
  { id = "openrouter"; display_name = "OpenRouter";
    routes = [ { name = "chat"; wire = Provider.Openai_completions;
      endpoint = "https://openrouter.ai/api/v1/chat/completions" } ];
    default_route = "chat";
    api_key_env = Some "OPENROUTER_API_KEY"; oauth = Some "openrouter" };
  { id = "together"; display_name = "Together AI";
    routes = [ { name = "chat"; wire = Provider.Openai_completions;
      endpoint = "https://api.together.ai/v1/chat/completions" } ];
    default_route = "chat";
    api_key_env = Some "TOGETHER_API_KEY"; oauth = None };
  { id = "cerebras"; display_name = "Cerebras";
    routes = [ { name = "chat"; wire = Provider.Openai_completions;
      endpoint = "https://api.cerebras.ai/v1/chat/completions" } ];
    default_route = "chat";
    api_key_env = Some "CEREBRAS_API_KEY"; oauth = None };
  { id = "venice"; display_name = "Venice";
    routes = [ { name = "chat"; wire = Provider.Openai_completions;
      endpoint = "https://api.venice.ai/api/v1/chat/completions" } ];
    default_route = "chat";
    api_key_env = Some "VENICE_API_KEY"; oauth = None };
  { id = "deepinfra"; display_name = "DeepInfra";
    routes = [ { name = "chat"; wire = Provider.Openai_completions;
      endpoint = "https://api.deepinfra.com/v1/openai/chat/completions" } ];
    default_route = "chat";
    api_key_env = Some "DEEPINFRA_API_KEY"; oauth = None };
  { id = "fireworks"; display_name = "Fireworks AI";
    routes = [ { name = "chat"; wire = Provider.Openai_completions;
      endpoint = "https://api.fireworks.ai/inference/v1/chat/completions" } ];
    default_route = "chat";
    api_key_env = Some "FIREWORKS_API_KEY"; oauth = None };
  { id = "baseten"; display_name = "Baseten";
    routes = [ { name = "chat"; wire = Provider.Openai_completions;
      endpoint = "https://inference.baseten.co/v1/chat/completions" } ];
    default_route = "chat";
    api_key_env = Some "BASETEN_API_KEY"; oauth = None };
  { id = "huggingface"; display_name = "Hugging Face Inference";
    routes = [ { name = "chat"; wire = Provider.Openai_completions;
      endpoint = "https://router.huggingface.co/v1/chat/completions" } ];
    default_route = "chat";
    api_key_env = Some "HF_TOKEN"; oauth = None };
  { id = "nanogpt"; display_name = "NanoGPT";
    routes = [ { name = "chat"; wire = Provider.Openai_completions;
      endpoint = "https://api.nano-gpt.com/api/v1/chat/completions" } ];
    default_route = "chat";
    api_key_env = Some "NANO_GPT_API_KEY"; oauth = None };
  { id = "aimlapi"; display_name = "AIML API";
    routes = [ { name = "chat"; wire = Provider.Openai_completions;
      endpoint = "https://api.aimlapi.com/v1/chat/completions" } ];
    default_route = "chat";
    api_key_env = Some "AIMLAPI_API_KEY"; oauth = None };
  { id = "aiand"; display_name = "ai&";
    routes = [ { name = "chat"; wire = Provider.Openai_completions;
      endpoint = "https://api.aiand.com/v1/chat/completions" } ];
    default_route = "chat";
    api_key_env = Some "AIAND_API_KEY"; oauth = None };
  { id = "gmi-cloud"; display_name = "GMI Cloud";
    routes = [ { name = "chat"; wire = Provider.Openai_completions;
      endpoint = "https://api.gmi-serving.com/v1/chat/completions" } ];
    default_route = "chat";
    api_key_env = Some "GMI_API_KEY"; oauth = None };
  { id = "abliteration"; display_name = "Abliteration AI";
    routes = [
      { name = "responses"; wire = Provider.Openai_responses;
        endpoint = "https://api.abliteration.ai/v1/responses" };
      { name = "chat"; wire = Provider.Openai_completions;
        endpoint = "https://api.abliteration.ai/v1/chat/completions" } ];
    default_route = "responses";
    api_key_env = Some "ABLITERATION_API_KEY"; oauth = None };
  { id = "sakana"; display_name = "Sakana AI";
    routes = [ { name = "responses"; wire = Provider.Openai_responses;
      endpoint = Sakana_api.sakana_responses_endpoint } ];
    default_route = "responses";
    api_key_env = Some "SAKANA_API_KEY"; oauth = None };
  { id = "lm-studio"; display_name = "LM Studio (local)";
    routes = [ { name = "chat"; wire = Provider.Local_chat;
      endpoint = "http://127.0.0.1:1234/v1/chat/completions" } ];
    default_route = "chat";
    api_key_env = Some "LM_STUDIO_API_KEY"; oauth = None };
  { id = "llama.cpp"; display_name = "llama.cpp (local)";
    routes = [ { name = "chat"; wire = Provider.Local_chat;
      endpoint = "http://127.0.0.1:8080/v1/chat/completions" } ];
    default_route = "chat";
    api_key_env = Some "LLAMA_CPP_API_KEY"; oauth = None };
  { id = "vllm"; display_name = "vLLM (local)";
    routes = [ { name = "chat"; wire = Provider.Local_chat;
      endpoint = "http://127.0.0.1:8000/v1/chat/completions" } ];
    default_route = "chat";
    api_key_env = Some "VLLM_API_KEY"; oauth = None };
  { id = "azure"; display_name = "Azure OpenAI (configured resource)";
    routes = [ { name = "responses"; wire = Provider.Azure_responses;
      endpoint = "" } ];
    default_route = "responses";
    api_key_env = Some "AZURE_OPENAI_API_KEY"; oauth = None };
  { id = "github-copilot"; display_name = "GitHub Copilot Chat (public github.com)";
    routes = [ { name = "chat"; wire = Provider.Copilot_chat;
      endpoint = Github_copilot_wire.endpoint } ];
    default_route = "chat";
    api_key_env = None; oauth = Some "github-copilot" };
]

let all () = builtins
let find id = List.find_opt (fun provider -> provider.id = id) builtins

(* These listings do not document enough API-route or tool metadata to certify
   that every returned ID works on the registered route. Manual IDs remain allowed. *)
let unclassified_models id =
  List.mem id [ "stepfun"; "synthetic"; "wafer-serverless"; "zenmux";
    "xiaomi"; "kilo"; "opencode-zen"; "opencode-go"; "charm-hyper";
    "yolo-auto"; "meta"; "vercel-ai-gateway"; "commandcode" ]

let route provider name =
  let name = if name = "" then provider.default_route else name in
  match List.find_opt (fun entry -> entry.name = name) provider.routes with
  | Some entry when Local_compat.engine provider.id <> None ->
      Some { entry with endpoint = Local_compat.endpoint ~provider:provider.id () }
  | Some entry when provider.id = "azure" ->
      Some { entry with endpoint = Azure_wire.endpoint () }
  | route -> route
